# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMTO-CNrXfHf9PFxlJCyN1HsfhZHPB1T

##Milestone Optimization for Brand Campaigns
"""

## Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

sns.set_style("whitegrid")

pd.set_option("display.max_columns", None)

np.random.seed(42)

##Load the Data

campaigns = pd.read_csv("campaigns.csv")
creators = pd.read_csv("creators.csv")
posts = pd.read_csv("posts.csv")
historical_ladders = pd.read_csv("historical_ladders.csv")

print("Campaigns :", campaigns.shape)
print("Creators :", creators.shape)
print("Posts :", posts.shape)
print("Historical Ladders :", historical_ladders.shape)

## Data Inspection

datasets = {
    "Campaigns": campaigns,
    "Creators": creators,
    "Posts": posts,
    "Historical Ladders": historical_ladders
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nShape:", df.shape)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nData Types:")
    print(df.dtypes)

    print("\n")

campaigns["start_date"] = pd.to_datetime(campaigns["start_date"])
campaigns["end_date"] = pd.to_datetime(campaigns["end_date"])

posts["post_date"] = pd.to_datetime(posts["post_date"])

posts.drop(
    columns=[
        "historical_avg_views_per_post",
        "historical_completion_rate"
    ],
    inplace=True
)

posts.head()

"""**Exploratory Data Analysis**

Campaign Categories
"""

plt.figure(figsize=(8,5))

sns.countplot(
    data=campaigns,
    x="category",
    order=campaigns["category"].value_counts().index
)

plt.title("Distribution of Campaign Categories")
plt.xlabel("Category")
plt.ylabel("Number of Campaigns")

plt.xticks(rotation=20)

plt.show()

"""Observation:
 Fashion and Gaming campaigns appear most frequentl in the dataset.

Target Creator Tier
"""

plt.figure(figsize=(7,5))

sns.countplot(
    data=campaigns,
    x="target_creator_tier",
    order=["Nano","Micro","Mid","Macro"]
)

plt.title("Target Creator Tier Distribution")
plt.xlabel("Creator Tier")
plt.ylabel("Number of Campaigns")

plt.show()

"""Campaign Budget Analysis"""

plt.figure(figsize=(8,5))

sns.histplot(
    campaigns["total_budget"],
    bins=20,
    kde=True
)

plt.title("Distribution of Campaign Budgets")
plt.xlabel("Budget")
plt.ylabel("Frequency")

plt.show()

"""Observation:
Most campaign budgets fall in the lower range, with only a few high-budget campaigns.

Creator Tier Distribution
"""

plt.figure(figsize=(7,5))

sns.countplot(
    data=creators,
    x="tier",
    order=["Nano","Micro","Mid","Macro"]
)

plt.title("Creator Distribution by Tier")
plt.xlabel("Creator Tier")
plt.ylabel("Number of Creators")

plt.tight_layout()
plt.show()

"""Observation:
Micro creators are targeted more often than Macro creators.

Historical Average Views by Tier
"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=creators,
    x="tier",
    y="historical_avg_views_per_post",
    order=["Nano","Micro","Mid","Macro"]
)

plt.title("Historical Average Views by Creator Tier")
plt.xlabel("Creator Tier")
plt.ylabel("Average Views per Post")

plt.tight_layout()
plt.show()

"""Observation:
Higher creator tiers generally receive more historical views than smaller creator tiers. This supports using creator tier when recommending milestone thresholds instead of applying the same ladder to every creator.

Distribution of Final Views
"""

plt.figure(figsize=(8,5))

sns.histplot(
    data=posts,
    x="views_final",
    bins=30,
    kde=True
)

plt.title("Distribution of Final Views")
plt.xlabel("Final Views")
plt.ylabel("Number of Posts")

plt.tight_layout()
plt.show()

"""Observation:
Final views are right-skewed, meaning a small number of posts perform exceptionally well.

View Growth Timeline
"""

view_growth = pd.DataFrame({
    "24 Hours": [posts["views_at_24h"].mean()],
    "7 Days": [posts["views_at_7d"].mean()],
    "30 Days": [posts["views_at_30d"].mean()],
    "Final": [posts["views_final"].mean()]
})

plt.figure(figsize=(8,5))

plt.plot(
    view_growth.columns,
    view_growth.iloc[0],
    marker="o",
    linewidth=2
)

plt.title("Average View Growth Over Time")
plt.xlabel("Time")
plt.ylabel("Average Views")

plt.grid(True)

plt.tight_layout()
plt.show()

"""Distribution of Total Payout"""

plt.figure(figsize=(8,5))

sns.histplot(
    data=posts,
    x="total_payout_earned",
    bins=25,
    kde=True
)

plt.title("Distribution of Total Payout Earned")
plt.xlabel("Total Payout")
plt.ylabel("Number of Posts")

plt.tight_layout()
plt.show()

"""##Milestone Optimization"""

# Merge all datasets so each post has campaign and creator details
analysis_df = (
    posts
    .merge(creators, on="creator_id", how="left")
    .merge(campaigns, on="campaign_id", how="left")
)

analysis_df.head()

milestone_ladders = (
    analysis_df
    .groupby(["category", "target_creator_tier"])["views_final"]
    .quantile([0.20, 0.40, 0.60, 0.80, 1.00])
    .unstack()
    .reset_index()
)

milestone_ladders.columns = [
    "category",
    "target_creator_tier",
    "Milestone_1",
    "Milestone_2",
    "Milestone_3",
    "Milestone_4",
    "Milestone_5"
]

milestone_ladders.head()

def recommend_milestones(category, creator_tier, total_budget):
    """
    Generating a milestone ladder for a campaign based on
    its category, creator tier and campaign budget.

    """


    recommendation = milestone_ladders[
        (milestone_ladders["category"] == category) &
        (milestone_ladders["target_creator_tier"] == creator_tier)
    ]


    if recommendation.empty:

        category_data = milestone_ladders[
            milestone_ladders["category"] == category
        ]

        if not category_data.empty:

            recommendation = (
                category_data[
                    [
                        "Milestone_1",
                        "Milestone_2",
                        "Milestone_3",
                        "Milestone_4",
                        "Milestone_5"
                    ]
                ]
                .mean()
                .to_frame()
                .T
            )


    if recommendation.empty:

        recommendation = (
            milestone_ladders[
                [
                    "Milestone_1",
                    "Milestone_2",
                    "Milestone_3",
                    "Milestone_4",
                    "Milestone_5"
                ]
            ]
            .mean()
            .to_frame()
            .T
        )

    recommendation = recommendation.iloc[0]

    payout_percentages = [0.10, 0.15, 0.20, 0.25, 0.30]

    result = pd.DataFrame({
        "Milestone": [
            "Milestone 1",
            "Milestone 2",
            "Milestone 3",
            "Milestone 4",
            "Milestone 5"
        ],
        "View Threshold": [
            int(round(recommendation["Milestone_1"])),
            int(round(recommendation["Milestone_2"])),
            int(round(recommendation["Milestone_3"])),
            int(round(recommendation["Milestone_4"])),
            int(round(recommendation["Milestone_5"]))
        ],
        "Payout": [
            int(round(total_budget * p))
            for p in payout_percentages
        ]
    })

    return result

# Apply the recommendation logic to every historical campaign
# so it can be compared with the existing milestone ladder.

recommended_campaigns = []

for _, row in campaigns.iterrows():

    ladder = recommend_milestones(
        category=row["category"],
        creator_tier=row["target_creator_tier"],
        total_budget=row["total_budget"]
    )

    ladder["campaign_id"] = row["campaign_id"]

    recommended_campaigns.append(ladder)

recommended_campaigns = pd.concat(
    recommended_campaigns,
    ignore_index=True
)

recommended_campaigns.head()

# Reshape the recommendations so they match the structure
# of the historical milestone data.

recommended_comparison = recommended_campaigns.copy()

recommended_comparison["milestone_rank"] = (
    recommended_comparison["Milestone"]
    .str.extract(r"(\d)")
    .astype(int)
)

recommended_comparison.rename(
    columns={
        "View Threshold": "recommended_threshold",
        "Payout": "recommended_payout"
    },
    inplace=True
)

recommended_comparison.head()

backtest = historical_ladders.merge(
    recommended_comparison[
        [
            "campaign_id",
            "milestone_rank",
            "recommended_threshold",
            "recommended_payout"
        ]
    ],
    on=["campaign_id", "milestone_rank"],
    how="inner"
)

backtest.head()

print(backtest.dtypes)

print(backtest[["recommended_threshold", "view_threshold"]].head())

backtest["threshold_difference"] = (
    backtest["recommended_threshold"]- backtest["view_threshold"]
)

backtest.head()

# Comparing historical and recommended payouts

backtest["payout_difference"] = (
    backtest["recommended_payout"]
    - backtest["payout_amount"]
)

backtest.head()

# Validating that recommended payouts stay within budget

budget_validation = (
    recommended_campaigns
    .groupby("campaign_id")["Payout"]
    .sum()
    .reset_index(name="recommended_total_payout")
)

budget_validation = budget_validation.merge(
    campaigns[["campaign_id", "total_budget"]],
    on="campaign_id",
    how="left"
)

budget_validation["within_budget"] = (
    budget_validation["recommended_total_payout"]
    <= budget_validation["total_budget"]
)

budget_validation.head()

summary = pd.DataFrame({

    "Metric": [
        "Average Threshold Difference",
        "Maximum Threshold Difference",
        "Average Payout Difference",
        "Maximum Payout Difference",
        "Campaigns Within Budget"
    ],

    "Value": [

        round(backtest["threshold_difference"].abs().mean(), 2),

        round(backtest["threshold_difference"].abs().max(), 2),

        round(backtest["payout_difference"].abs().mean(), 2),

        round(backtest["payout_difference"].abs().max(), 2),

        f"{budget_validation['within_budget'].sum()} / {len(budget_validation)}"

    ]

})

summary

# ==========================================
# Interactive Testing - New Campaign
# ==========================================

print("\n====== Test a New Campaign ======\n")

categories = sorted(campaigns["category"].unique())
tiers = sorted(campaigns["target_creator_tier"].unique())

print("Available Categories:")
for i, cat in enumerate(categories, start=1):
    print(f"{i}. {cat}")

category = categories[int(input("\nSelect Category (number): ")) - 1]

print("\nAvailable Creator Tiers:")
for i, tier in enumerate(tiers, start=1):
    print(f"{i}. {tier}")

creator_tier = tiers[int(input("\nSelect Creator Tier (number): ")) - 1]

budget = float(input("\nEnter Campaign Budget: "))

result = recommend_milestones(
    category=category,
    creator_tier=creator_tier,
    total_budget=budget
)

display_result = result.copy()

display_result["View Threshold"] = display_result["View Threshold"].apply(lambda x: f"{int(x):,}")
display_result["Payout"] = display_result["Payout"].apply(lambda x: f"{int(x):,}")

display(display_result)